# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mengyue Wu
tagline:          'Online portfolio'
description:      'Persuing Master of Information Technology in Carnegie Mellon University'
url:              https://menyw.github.io/
baseurl:          '/'

author:
  name:           'Mengyue Wu'
  url:            https://www.linkedin.com/in/mengyuew/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
