# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mengyue Wu
tagline:          'Online portfolio'
description:      'This webpage was originally completed as a coursework for the 94870-Telling story with data. But I plan to make this page my personal website. I will modify the site description later.'
url:              https://menyw.github.io/
baseurl:          '/'

author:
  name:           'Mengyue Wu'
  url:            https://www.linkedin.com/in/mengyuew/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/poole/hyde
