# Dependencies
# markdown:         kramdown
# highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Mengyue Wu
tagline:          'Online portfolio'
description:      'Persuing Master of Information Technology in <a href="https://www.cmu.edu">Carnegie Mellon University</a>'
url:              https://menyw.github.io/
baseurl:          '/'

author:
  name:           'Mengyue Wu'
  url:            https://www.linkedin.com/in/mengyuew/

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/menyw/menyw.github.io
